name: first 

on: push

jobs:
  job1:
    name: first_job
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: actions/checkout@v2
      - name: step2
        run: date

  job2:
    name: second_job
    runs-on: windows-latest
    steps:
      - name: step1
        uses: actions/checkout@v2
      - name: step2
        run: date /t
  job3:
    name: third_job
    runs-on: macos-latest
    steps:
      - name: step1
        uses: actions/checkout@v2
      - name: step2
        run: date 
  job4:
    name: forth_job
    runs-on: ubuntu-22.04
    steps:
      - name: step1
        uses: actions/checkout@v2
      - name: step2
        run: date 

